FROM node:16-alpine

# /app 디렉터리를 WORKDIR로 설정
WORKDIR /app

# chromium 설치
RUN apk add --no-cache \
  chromium \
  nss \
  freetype \
  harfbuzz \
  ca-certificates \
  ttf-freefont

# npm install 시 Chromium 다운로드 제외 처리
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
  PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

CMD ["yarn", "start:debug"]